const actions = {
  SET_MODAL: "SET_MODAL",
  CLEAR_FLIGHTS: "CLEAR_FLIGHTS",
  GET_FLIGHTS: "GET_FLIGHTS",
  GET_FLIGHTS_RETURN: "GET_FLIGHTS_RETURN",
  FLIGHT_INFO: "FLIGHT_INFO",
  FLIGHT_COUNT: "FLIGHT_COUNT",
  FLIGHT_DAY: "FLIGHT_DAY",
  SHOW_DETAILS: "SHOW_DETAILS",
  SHOW_RETURN_DETAILS: "SHOW_RETURN_DETAILS",
  SELECT_ONE_WAY: "SELECT_ONE_WAY",
  SELECT_RETURN: "SELECT_RETURN",
  SET_TRIP: "SET_TRIP",
  SET_ORIGIN_CITY: "SET_ORIGIN_CITY",
  SET_DEST_CITY: "SET_DEST_CITY",
  SET_DEP_DATE: "SET_DEP_DATE",
  SET_RETURN_DATE: "SET_RETURN_DATE",
  SET_PASSENGER_COUNT: "SET_PASSENGER_COUNT"
}

module.exports = actions;
